# Generated by Django 5.2.2 on 2025-06-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatushistory',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
