# Generated by Django 5.2.2 on 2025-06-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cartitem_cart_alter_cartitem_product'),
    ]

    operations = [
    ]
